import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, Shield, BookOpen, Link as LinkIcon, AlertTriangle } from 'lucide-react'
import { Button } from '@/components/ui'
import { SEO } from '@/components/SEO'

export function EthicsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="AI Ethics & Guidelines"
        description="Our ethical guidelines for AI summarization, source attribution, and content handling at Upday."
        url="/ethics"
      />

      <header className="border-b border-border">
        <div className="max-w-2xl mx-auto px-4 py-4">
          <Button variant="ghost" size="sm" onClick={() => navigate('/')}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </div>
      </header>

      <main id="main-content" className="max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-foreground mb-6">AI Ethics & Guidelines</h1>

        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <p className="text-lg text-muted-foreground mb-8">
            Upday uses AI to summarize news articles. Here's how we approach this responsibility.
          </p>

          <section className="mb-12">
            <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
              <Shield className="h-5 w-5 text-primary" />
              AI Summarization Transparency
            </h2>
            <p className="text-muted-foreground mb-4">
              Every summary on Upday is generated by AI, specifically large language models.
              These summaries are designed to capture key information but may not include
              all nuances from the original article.
            </p>
            <p className="text-muted-foreground mb-4">
              AI summaries can occasionally:
            </p>
            <ul className="text-muted-foreground list-disc list-inside mb-4 space-y-1">
              <li>Miss important context or caveats</li>
              <li>Oversimplify complex topics</li>
              <li>In rare cases, misinterpret the original content</li>
            </ul>
            <p className="text-muted-foreground">
              For this reason, we always link to the original source and encourage readers
              to click through for the full story.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-primary" />
              Content Integrity
            </h2>
            <p className="text-muted-foreground mb-4">
              We do not alter the meaning or intent of source articles.
              AI summaries aim to condense, not interpret or editorialize.
            </p>
            <p className="text-muted-foreground">
              We do not add opinions, take positions on stories, or modify facts
              from the original reporting.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
              <LinkIcon className="h-5 w-5 text-primary" />
              Source Attribution
            </h2>
            <p className="text-muted-foreground mb-4">
              Every article on Upday displays the original source and links directly
              to the original publication. We believe journalists and publications
              deserve credit and traffic for their work.
            </p>
            <p className="text-muted-foreground">
              We do not rehost full articles. Upday is a discovery tool that drives
              readers to original content.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-primary" />
              User Responsibility
            </h2>
            <p className="text-muted-foreground mb-4">
              While we strive for accuracy in our AI summaries, users should:
            </p>
            <ul className="text-muted-foreground list-disc list-inside mb-4 space-y-1">
              <li>Read original sources for important decisions</li>
              <li>Verify claims through multiple sources</li>
              <li>Be aware that news can be updated after we summarize it</li>
              <li>Report inaccurate summaries through our feedback system</li>
            </ul>
          </section>

          <section className="border-t border-border pt-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Report Issues</h2>
            <p className="text-muted-foreground">
              Found an inaccurate summary or have concerns about our content?
              Please let us know on our{' '}
              <Link to="/feedback" className="text-primary hover:underline">
                feedback page
              </Link>
              . We take accuracy seriously and will investigate all reports.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
